import { tcv } from "@choice-ui/shared"

export const mdRenderTv = tcv({
  slots: {
    root: "max-w-none",
    paragraph: "",
    h1: "",
    h2: "",
    h3: "",
    h4: "",
    h5: "",
    h6: "",
    ul: "",
    ol: "",
    li: "",
    blockquote: "",
    hr: "",
    a: "",
    code: "",
    codeBlock: "",
    pre: "",
    table: "",
    th: "",
    td: "",
    tr: "",
    thead: "",
    tbody: "",
    tableWrapper: "h-auto",
    strong: "",
    em: "",
    del: "",
    img: "",
    checkbox: "md-checkbox",
    checkboxIcon: "size-4 rounded-md bg-default-foreground/10",
  },
  variants: {
    size: {
      default: {},
      small: {
        root: "md-compact",
      },
      large: {
        root: "md-large",
      },
    },
    variant: {
      github: {
        root: "github-md",
        tableWrapper: "table-wrapper",
      },
      default: {
        root: "md",
        paragraph: "md-p",
        h1: "md-h1",
        h2: "md-h2",
        h3: "md-h3",
        h4: "md-h4",
        h5: "md-h5",
        h6: "md-h6",
        ul: "md-ul",
        ol: "md-ol",
        li: "md-li",
        blockquote: "md-blockquote",
        hr: "md-hr",
        a: "md-a",
        code: "md-code",
        codeBlock: "md-code-block",
        pre: "md-pre",
        table: "md-table",
        th: "md-th",
        td: "md-td",
        tr: "md-tr",
        thead: "md-thead",
        tbody: "md-tbody",
        tableWrapper: "md-table-wrapper",
        strong: "md-strong",
        em: "md-em",
        del: "md-del",
        img: "md-img",
      },
    },
    hasCheckbox: {
      true: {
        li: "md-li-task",
      },
      false: {},
    },
  },
  defaultVariants: {
    size: "default",
    variant: "default",
    hasCheckbox: false,
  },
})
