// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'cn'

export type Locales =
	| 'cn'
	| 'us'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 加​载​中​.​.​.
		 */
		loading: string
	}
	menus: {
		/**
		 * 搜​索​结​果​为​空​，​请​尝​试​其​他​关​键​词
		 */
		searchEmpty: string
		/**
		 * 清​空
		 */
		searchEmptyButton: string
	}
	numberInput: {
		/**
		 * 添​加​变​量
		 */
		addVariable: string
		/**
		 * 移​除​变​量
		 */
		detachVariable: string
	}
	chip: {
		/**
		 * 标​签
		 */
		chip: string
		/**
		 * 移​除​标​签​：​{​c​h​i​p​}
		 * @param {unknown} chip
		 */
		remove: RequiredParams<'chip'>
	}
	comments: {
		/**
		 * 添​加​表​情
		 */
		emoji: string
		/**
		 * 添​加​提​及
		 */
		mention: string
		/**
		 * 上​传​最​多​5​张​图​片
		 */
		attachment: string
		/**
		 * 提​交
		 */
		submit: string
		/**
		 * 移​除​图​片
		 */
		removeImage: string
		/**
		 * 添​加​评​论
		 */
		addComment: string
		/**
		 * 评​论​操​作
		 */
		actions: string
		/**
		 * 编​辑​.​.​.
		 */
		edit: string
		/**
		 * 删​除​评​论
		 */
		'delete': string
		/**
		 * 添​加​表​情
		 */
		reactions: string
		/**
		 * 加​载​更​多​评​论
		 */
		loadMoreComments: string
	}
	picturePreview: {
		/**
		 * 放​大
		 */
		zoomIn: string
		/**
		 * 缩​小
		 */
		zoomOut: string
		/**
		 * 重​置
		 */
		zoomReset: string
		/**
		 * 适​应​屏​幕
		 */
		fitToScreen: string
		/**
		 * 放​大​到​5​0​%
		 */
		zoomTo50: string
		/**
		 * 放​大​到​1​0​0​%
		 */
		zoomTo100: string
		/**
		 * 放​大​到​2​0​0​%
		 */
		zoomTo200: string
		/**
		 * 图​片​加​载​失​败​，​请​稍​后​再​试​。
		 */
		error: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 加载中...
		 */
		loading: () => LocalizedString
	}
	menus: {
		/**
		 * 搜索结果为空，请尝试其他关键词
		 */
		searchEmpty: () => LocalizedString
		/**
		 * 清空
		 */
		searchEmptyButton: () => LocalizedString
	}
	numberInput: {
		/**
		 * 添加变量
		 */
		addVariable: () => LocalizedString
		/**
		 * 移除变量
		 */
		detachVariable: () => LocalizedString
	}
	chip: {
		/**
		 * 标签
		 */
		chip: () => LocalizedString
		/**
		 * 移除标签：{chip}
		 */
		remove: (arg: { chip: unknown }) => LocalizedString
	}
	comments: {
		/**
		 * 添加表情
		 */
		emoji: () => LocalizedString
		/**
		 * 添加提及
		 */
		mention: () => LocalizedString
		/**
		 * 上传最多5张图片
		 */
		attachment: () => LocalizedString
		/**
		 * 提交
		 */
		submit: () => LocalizedString
		/**
		 * 移除图片
		 */
		removeImage: () => LocalizedString
		/**
		 * 添加评论
		 */
		addComment: () => LocalizedString
		/**
		 * 评论操作
		 */
		actions: () => LocalizedString
		/**
		 * 编辑...
		 */
		edit: () => LocalizedString
		/**
		 * 删除评论
		 */
		'delete': () => LocalizedString
		/**
		 * 添加表情
		 */
		reactions: () => LocalizedString
		/**
		 * 加载更多评论
		 */
		loadMoreComments: () => LocalizedString
	}
	picturePreview: {
		/**
		 * 放大
		 */
		zoomIn: () => LocalizedString
		/**
		 * 缩小
		 */
		zoomOut: () => LocalizedString
		/**
		 * 重置
		 */
		zoomReset: () => LocalizedString
		/**
		 * 适应屏幕
		 */
		fitToScreen: () => LocalizedString
		/**
		 * 放大到50%
		 */
		zoomTo50: () => LocalizedString
		/**
		 * 放大到100%
		 */
		zoomTo100: () => LocalizedString
		/**
		 * 放大到200%
		 */
		zoomTo200: () => LocalizedString
		/**
		 * 图片加载失败，请稍后再试。
		 */
		error: () => LocalizedString
	}
}

export type Formatters = {}
