// 从 typography.ts 自动提取的数据
// 生成时间: 2025-06-20T02:58:22.584Z

module.exports = {
  fontFamilies: {
    default: [
      "Inter",
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      "BlinkMacSystemFont",
      "Segoe UI",
      "Roboto",
      "Helvetica Neue",
      "Arial",
      "Noto Sans",
      "sans-serif",
      "SFProLocalRange",
    ],
    display: [
      "Whyte",
      "ui-sans-serif",
      "system-ui",
      "-apple-system",
      "BlinkMacSystemFont",
      "Segoe UI",
      "Roboto",
      "Helvetica Neue",
      "Arial",
      "Noto Sans",
      "sans-serif",
    ],
    mono: [
      "Roboto Mono",
      "Monaco",
      "Courier New",
      "SFMono-Regular",
      "Menlo",
      "Consolas",
      "monospace",
    ],
  },
  fontWeights: {
    light: 400,
    default: 450,
    medium: 450,
    semibold: 500,
    strong: 550,
    heavy: 550,
  },
  fontSizes: {
    xs: "0.5625rem",
    sm: "0.6875rem",
    md: "0.8125rem",
    lg: "0.9375rem",
    xl: "1.5rem",
    "2xl": "3rem",
  },
  "line-heights": {
    tight: "0.875rem",
    snug: "1rem",
    normal: "1.375rem",
    relaxed: "1.5625rem",
    loose: "2rem",
    "extra-loose": "3.5rem",
  },
  "letter-spacings": {
    "body-large": "-0.002rem",
    "body-medium": "0.00344rem",
    "body-small": "0.00281rem",
    "body-small-strong": "0.016875rem",
    "heading-large": "-0.0255rem",
    "heading-medium": "-0.00469rem",
    "heading-small": "-0.002rem",
    display: "-0.09rem",
  },
  bodyTypography: {
    "body-large": {
      fontFamily: "default",
      fontSize: "md",
      fontWeight: "default",
      lineHeight: "normal",
      letterSpacing: "body-large",
    },
    "body-large-strong": {
      fontFamily: "default",
      fontSize: "md",
      fontWeight: "strong",
      lineHeight: "normal",
      letterSpacing: "body-large",
    },
    "body-medium": {
      fontFamily: "default",
      fontSize: "sm",
      fontWeight: "medium",
      lineHeight: "snug",
      letterSpacing: "body-medium",
    },
    "body-medium-strong": {
      fontFamily: "default",
      fontSize: "sm",
      fontWeight: "heavy",
      lineHeight: "snug",
      letterSpacing: "body-medium",
    },
    "body-small": {
      fontFamily: "default",
      fontSize: "xs",
      fontWeight: "default",
      lineHeight: "tight",
      letterSpacing: "body-small",
    },
    "body-small-strong": {
      fontFamily: "default",
      fontSize: "xs",
      fontWeight: "strong",
      lineHeight: "tight",
      letterSpacing: "body-small-strong",
    },
  },
  headingTypography: {
    "heading-display": {
      fontFamily: "display",
      fontSize: "2xl",
      fontWeight: "light",
      lineHeight: "extra-loose",
      letterSpacing: "display",
    },
    "heading-large": {
      fontFamily: "default",
      fontSize: "xl",
      fontWeight: "heavy",
      lineHeight: "loose",
      letterSpacing: "heading-large",
    },
    "heading-medium": {
      fontFamily: "default",
      fontSize: "lg",
      fontWeight: "heavy",
      lineHeight: "relaxed",
      letterSpacing: "heading-medium",
    },
    "heading-small": {
      fontFamily: "default",
      fontSize: "md",
      fontWeight: "heavy",
      lineHeight: "normal",
      letterSpacing: "heading-small",
    },
  },
  typographyPresets: {},
};
